language: go

go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: false

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
